all: \
	iso/music/menu.xa \
	iso/songs/1.xa \

# XA converts
iso/%.xa: iso/%.ogg
	tools/psxavenc/psxavenc -f 37800 -t xa -b 4 -c 2 -F 1 -C 0 $< $@ 

iso/%.xa:
	tools/xainterleave/xainterleave $@ $^

# Menu
iso/music/menu.xa: iso/music/freakymenu.xa iso/music/gameover.xa

# 1
iso/songs/1.xa: iso/songs/2torial/Merged.xa iso/songs/2torial/Inst.xa iso/songs/free-4-me/Merged.xa iso/songs/free-4-me/Inst.xa
